---
- name: Add bender user
  user:
    name: bender
    shell: /bin/bash
    groups: sudo
    append: yes
  become: true
- name: Install ZSH
  include_role:
    name: maxbbender.ansible_role_zsh
  vars:
    target_user: bender